project:
  type: website

website:
  title: "Projet visualisation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - p2022.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

